### ISSUE TITLE
Question on distributed system

### ISSUE THREAD

**Issue by rofenix2** [TheArchitectDev/Architect.Identities#38]
Hi, great project, but something is not clear, assuming that two machines generates a distributed id at the same millisecond, the timestamp part will be the same, there will be no monotonic increment since there is no centralized coordinator right?.

Also is this project a hobby/test or will it get long time support?. I am kind of thinking in using it instead of ULIDs but i am afraid that it will later get archived or forgotten.

Thanks.

**Comment by Timovzl** [comment]
Hi @cdrfenix,

This Architect packages are in production use at multiple organizations and are being actively maintained. In fact, various new major versions have been released this year. (Additionally, the open source license makes it possible to fork the repos and maintain your own versions, although this should not be necessary.)

You are correct: When two machines generate a DistributedId on the same millisecond, there is no definitive ordering between the two. I would ask you to consider the usefulness if it were. The clocks of those machines are likely not aligned to the exact same millisecond in the first place. Also, if two machines are handling requests simultaneously, there are many factors that can cause one to be faster than the other.

Do you see any purpose for the concept of a definitive ordering between IDs generated on separate machines? The use cases I can come up with only benefit from a definitive ordering _inside one process_, i.e. within a machine.

**Comment by rofenix2** [comment]
Thanks for the answer and glad that the packages are in production. My question was more for the usage of DistributedId as a clustered index and related to index fragmentation, the usual case with K-sorted sequences, not that i care much about it since ULID is the same in that regard, just confirming for clarification.

Also would you mind answering why the documentation says the usage context could be for medium-size companies?. I get that they are not globally unique and are not 128bit long, but i doubt you run out even in the most big ecommerce platform for example. I am not a expert in the field but 2^93 seems pretty high, is there something that i am not taking into account for such a statement?.

**Comment by Timovzl** [comment]
Ah, I understand. Indeed, multi-machine insertions on the same millisecond are not necessarily sequential, which can indeed lead to somewhat more empty space in pages on very busy systems. The benefit is primarily that the writes all go to the last page rather than to random pages.

I agree with you that this is the case for most such ID generation schemes. Synchronization tends to cost more than it helps.

> Also would you mind answering why the documentation says the usage context could be for medium-size companies?

Yes, the claims are being conservative and aimed more at the expectation of guarantees. A medium-sized company _can generally expect zero collisions_. If a Google-sized company would choose this scheme _and_ then expect zero collisions forever on a system running on thousands of machines, they might be disappointed. It’s still perfectly fine to use for that scenario, but with the knowledge that such extreme concurrency _could_ result in the occasional, rare collision.

Even then, the odds are extremely small. How could you produce collisions? Run on hundreds of thousands of machines _and_ have them generate IDs at the maximum rate _and_ simultaneously _and_ for prolonged periods of time. Why? On the same millisecond, the first random number is one of 2^48 possibilities. Next random numbers keep adding a value out of one of 2^41 possibilities. As such, with _continuous, concurrent, nonstop_ generation, the odds are bound by that 2^41.

In practical terms, this is the equivalent of Google regularly running a very long batch job that generates billions of items, running spread out over many servers. (And batch jobs tend to run on a single machine.) It remains an unlikely scenario.

As a related sneak peek, a 128-bit DistributedId variant will be added in the future. It has practically no rate limit or collisions. It also serves as a drop-in UUID replacement, and actually also satisfies the properties of the proposed v7 UUID. The downside is that there is no universal, obvious way to both represent _and_ order it, like with DistributedId’s simple decimal format. UUID ordering is… unwieldy.

**Comment by rofenix2** [comment]
I will use this library then, i was using ULID and converting it to uniqueidentifier in MSSQL. In the process i was taking the ulid timestamp and putting in it the uniqueidentifier last 48bits where Microsoft choose to sort it first. Anyway with DistributedIds is more simple and i can use decimal, probably a little more optimization than uniqueidentifier and the shorter alphanumeric representation its a good plus, although i will miss the base32 crockford encoding since its case insensitive. This library seems the only one that does the job in C# as generating unique ids and using them as clustered index with all the pros and little cons.

Also a 128-bit version would be nice, but its in own workspace... most of the people i see looking for unique IDs generator struggle with the concept that they are unordered and fear degrading the DB performance, since in google there are a lot of threads till this day about monotonic keys vs UUIDs. Which i am not sure with all the new hardware and cloud services is still a valid discussion.

Thanks for your time.

**Comment by Timovzl** [comment]
Glad to help.

Feel free to take the decimal, use the included BinaryIdEncoder to gets its bytes (in big endian), and encode those using base32 or any other encoding you like. It’s easy enough to write your own extension method to obtain a string from a decimal this way - or that’s how I would do it.

Note that a hexadecimal encoder is included out-of-the-box. They result is longer, but you wouldn’t have to write anything.

Base32 was not included, with the idea of optimizing for either shortness (base62) or case-ignorance and simplicity of character set (decimal). But base32 is a perfectly valid middle ground, of course.
