### ISSUE TITLE
SQLite :: decimal.ToAlphanumeric() causes exception

### ISSUE THREAD

**Issue by ebarkalov** [TheArchitectDev/Architect.Identities#39]
Hello! 😀

Thank you so much for sharing and maintaining such a great library!

Faced one problem when using SQLite database provider with EF and wonder if you could give suggestions on how to resolve it.

When using SQLite, decimal IDs are stored as **"text"** despite invocation of **ConfigureDecimalIdTypes()**. I believe that's because SQLite does not support DECIMALS with such high precision. When ID value is stored in the database, looks like ToString() generated method is used to convert number to a **text** database type:

```
public override string ToString()
{
  return this.Value.ToString("0.#");
}
```

As a result, decimal value is stored something like this: 1098956916504943605256135935.0 (note the trailing ".0").

Now, when trying to call ToAlphanumeric() on that value, exception is thrown:

`System.ArgumentException: The ID must be positive, have no decimal places, and consist of no more than 28 digits. (Parameter 'id')`

Looks like it does not like trailing decimal place ".0".

How would you suggest to resolve this? Either not store decimal place in the database or modify ToAlphanumeric() to disregard it?

Thank you! 🙏

**Comment by Timovzl** [comment]
Hi again @ebarkalov!

I see you have encountered this detail from the 2.0.0 change log:

`BREAKING: Decimal IDs in SQLite may get reconstituted with a one (inadvertent) decimal place, e.g. "1234567890123456789012345678" => "1234567890123456789012345678.0". Detecting and fixing for SQLite is a hassle.`

As a workaround that you may or may not like, I personally prefer to use SQL Server for testing nowadays. Locally, its "LocalDB" spins up automatically and should work for all developers on Windows. In testing pipelines, I use a SQL Server Docker image.

But let's say that's not what you're looking for right now.

Off the top of my head, we can fix this problem with a conversion. Let's take a look.

**SQLite only**

The annoying thing is that you _only_ want that conversion when using SQLite. Supposedly, the project doing your database mappings has no knowledge of SQLite, since that is testing-only. Instead, use something like `if (!dbContext.IsSqlServer())` to detect that you are _not_ using your regular database. If the condition is true, we can set a custom conversion.

**Conversion**

~~The conversion itself can be something like this:~~

```cs
.HasConverter(
   codeValue => codeValue.ToString("F0", CultureInfo.InvariantCulture)
   dbValue => Decimal.Truncate(Decimal.Parse(dbValue, CultureInfo.InvariantCulture)))
```

- ~~This fixes the conversion on the forward end, i.e. by converting to a string with 0 decimal places.~~
- ~~This fixes the conversion on the reverse end, i.e. by truncating after parsing.~~

~~The truncation _should_ be superfluous. You can try. Please let me know, for future reference!~~

_Edit:_ On second thought, the string conversion probably does not work, since the whole issue is that EF expects a decimal on the provider side, with the _database provider_ doing the string conversions. That leaves us to do a decimal-decimal conversion that fixes the problem during deserialization:

```cs
.HasConverter(codeValue => codeValue, dbValue => Decimal.Truncate(dbValue))
```

**All IDs**

You probably want to apply this conversion to all ID-like types.

You can either loop through each property of each entity, or you can add a custom `IPropertyAddedConvention`. I prefer the latter. The documentation has examples on how to add one.

Whichever you choose, have it filter on ID-like properties of the desired types:

```cs
// ID properties only
if (!propertyBuilder.Metadata.Name.EndsWith("Id") && !propertyBuilder.Metadata.Name.EndsWith("ID"))
	return;

// Decimal properties only
if (propertyBuilder.Metadata.ClrType != typeof(decimal))
	return;
```

Note that I have not accounted for nullable decimals here. Also, if you want to use wrapper value objects around a decimal, you can imitate an internal method from the package:

```cs
/// <summary>
/// Determines whether the given type is a type (or nullable wrapper thereof) that is <see cref="Decimal"/> or is convertible to and from it.
/// </summary>
internal static bool IsDecimalConvertible(Type type)
{
	// Dig through nullable
	if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>))
		type = type.GenericTypeArguments[0];

	// Short-circuit for decimals
	if (type == typeof(decimal))
		return true;

	// Must have explicit OR implicit conversion from decimal
	if (type.GetMethod("op_Explicit", genericParameterCount: 0, ParameterListWithSingleDecimal) is null && // Compiler enforces that return type is the type itself
		type.GetMethod("op_Implicit", genericParameterCount: 0, ParameterListWithSingleDecimal) is null) // Compiler enforces that return type is the type itself
		return false;

	// Must have implicit conversion to decimal
	if (!type.GetMethods(BindingFlags.Static | BindingFlags.Public)
		.Any(method => method.Name == "op_Implicit" && method.ReturnType == typeof(decimal))) // Compiler enforces single parameter of the type itself
		return false;

	return true;
}
```

Please let me know how this turns out. If a solution works well, I might be able to automate it into the package. (For example, by detecting at the last moment any decimals being mapped to strings, and adding custom conversions for those.)

**Comment by Timovzl** [comment]
I have published a possible fix in Architect.Identities.EntityFramework 2.1.0 preview. Please try it out.

When reading, any decimal IDs mapped using `ConfigureDecimalIdTypes()` now have their database values truncated before being [cast and] returned.

**Comment by ebarkalov** [comment]
Hi @Timovzl 

Thank you so much for such a quick reply! I implemented and was about to test suggested changes when you already submitted a fix! That's phenomenal! 😂

I do confirm SQLite decimal conversion works as expected now.

Thank you so much!!! 🙏

**Comment by Timovzl** [comment]
@ebarkalov Could you give the updated preview version a shot? I've adjusted the truncation to only truncate if the resulting value will be equal. I wanted to make sure that it still works right for you.

**Comment by ebarkalov** [comment]
Hi @Timovzl 
Thank you for your message!
I do confirm it continues to work!
